name: SonarCloud Scan

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17  # Install Java 17 manually
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Verify Java Version  # Debugging Step
        run: java -version

      - name: Set JAVA_HOME  # Ensure SonarCloud uses Java 17
        run: echo "JAVA_HOME=$(which java)" >> $GITHUB_ENV

      - name: Run SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          JAVA_HOME: "/usr/lib/jvm/java-17-openjdk-amd64"  # Force Java 17
